baseURL = "https://www.y103.org/"
author = "yjuba"
copyright = "www.y103.org is licensed under CC-BY-4.0."
paginate = 9
languageCode = "ja"
defaultContentLanguage = "ja"
enableInlineShortcodes = true

theme = "paper"
title = "www.y103.org"

publishDir = "docs"
staticDir = ["static"]

[params]
color = "linen"

twitter = "yutaka_j08"
github = "yjuba"

avatar = "https://www.y103.org/android-chrome-512x512.png"
name = "yjuba"
bio = "内製クラウドの雲の中を飛んでいる鳥類。嵐に巻き込まれたので情シスの木で雨宿り中。"

[permalinks]
post = "/post/:year/:month/:title/"

[markup]

[markup.goldmark.renderer]
unsafe = true

[services]

[services.twitter]
disableInlineCSS = true
