baseURL = "https://www.y103.org/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "www.y103.org"
theme = "hugo-theme-my-blog"
publishDir = "docs"

pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = true
# googleAnalytics = "UA-176946145-1"
copyright = "www.y103.org is licensed under CC-BY-4.0."

[author]
  name = "yjuba"

[params]
  dateformat = "2006/01/02"

[permalinks]
  post = "/post/:year/:month/:title/"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.youtube]
    privacyEnhanced = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true
